Fix a bug in older firefox versions
hashicorp/react-components pull request #454
Opened 2021-12-06 21:03 UTC by jescalan

🎟️ [Asana Task]()
🔍 [Preview Link](https://react-components-git-{branch-slug}-hashicorp.vercel.app)

---

## Description

Potentially fixes https://github.com/hashicorp/vault/issues/13350

Tested in saucelabs, breaking down [the shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/flex) seems to resolve the issue.

### PR Checklist 🚀

Items in this checklist may not may not apply to your PR, but please consider each item carefully.

- [ ] Add Asana and Preview links above.
- [ ] Conduct thorough self-review.
- [ ] Add or update tests as appropriate.
- [ ] Conduct reasonable cross browser testing for both compatibility and responsive behavior (We have a [Sauce Labs](https://app.saucelabs.com/) account for this, if you don't have access, just ask!).
- [ ] Conduct reasonable accessibility review (use the [WAS](https://accessible.org/Web-Accessibility-Standards-WAS-2.pdf) as a guide or an [axe browser plugin](https://www.deque.com/axe/) until we establish more formal checks).
- [ ] Identify (in the description above) and document (add Asana tasks on [this board](https://app.asana.com/0/1100423001970639/list)) any technical debt that you're aware of, but are not addressing as part of this PR.

2021-12-06 21:53 UTC, dstaley commented
Applying the expanded form doesn't seem to resolve the issue for me in 78esr

![image](https://user-images.githubusercontent.com/88163/144928627-4024f068-c6b6-476a-ae2c-4c9dfcc041df.png)

2021-12-06 21:59 UTC, jescalan commented
@dstaley could you try again but with dropping the `flex-basis`? I just adjusted the PR for this 😬

2021-12-06 22:14 UTC, dstaley commented
> @dstaley could you try again but with dropping the `flex-basis`? I just adjusted the PR for this 😬

Negative ghost rider.

![image](https://user-images.githubusercontent.com/88163/144931271-071aaa6c-9b40-4f53-9dd0-77740df6c2b9.png)

2021-12-07 01:56 UTC, jescalan commented
@dstaley ah you also need to disable `flex` declaration attached directly to the selector for it to kick in 😁

2021-12-07 20:21 UTC, zchsh commented
Tested on SauceLabs, I think I'm seeing the same thing as @dstaley . When I add `min-width: 0` to `#inner` it seems to resolve the issue though 👍 I think this has to do with how the default `min-width: auto` works in `flex` contexts (https://drafts.csswg.org/css-flexbox/#min-size-auto) but am unclear on the details (have just ran into this before!).

2021-12-07 20:23 UTC, zchsh commented
<img width="1887" alt="CleanShot 2021-12-07 at 15 22 49@2x" src="https://user-images.githubusercontent.com/4624598/145100732-1d1facb4-c534-4a69-8061-03e96a3f6249.png">

2021-12-07 20:30 UTC, zchsh commented
Edit: looked into this a bit more and found a simpler fix. It seems that the defaults for `flex-basis` have changed over time. Explicitly setting  `flex: 1 1 auto` seems to resolve the issue as well.

![CleanShot 2021-12-07 at 15 27 53@2x](https://user-images.githubusercontent.com/4624598/145101557-994d8810-8b27-4669-b895-cc0a0e62bcf3.png)

2021-12-07 20:34 UTC, zchsh requested changes

2021-12-07 20:34 UTC, zchsh commented on packages/docs-page/style.module.css
> +    flex-shrink: 1;
I'm honestly having trouble understanding all the nuance both of flex-basis and how it has changed over the years (https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis#values). But taking a more pragmatic approach, the CSS below seems to work both in FireFox 78 and in newer browsers:

```suggestion
    flex: 1 1 auto;
```

As an alternate solution, this also seems to work:

```suggestion
    flex: 1 1;
    min-width: 0;
```

2021-12-07 23:27 UTC, jescalan commented
Sounds good, applied the suggestion!

2021-12-16 19:22 UTC, zchsh approved these changes

2021-12-16 19:23 UTC, zchsh commented
💖 ☝️ Sorry for the delay 😬

2021-12-21 23:49 UTC, merged